version: '3'
services:
  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
      -  /var/postgresql/data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - postgresql
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "christian.cavuti@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password123"
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - postgresql
networks:
  postgresql:
    driver: bridge